=encoding utf8

=head1 NAME

MBMan - Eine IMAP Mailboxmanagement API.

=head1 ANWENDUNG

use MBMan;

my $mbman = MBMan->new();

$mbman->connect(
    Server => 'imap.server.tld'
);

$mbman->login(
    User => 'user@domain.tld',
    Password => 'pa$$w0rd'
);

$mbman->new_database();

$mbman->unshift_message() if mbman->limit_reached();

$mbman->logout();


=head1 OBJEKT-METHODEN

In diesem Kapitel sind die Methoden aufgeführt, die auf ein MBMan-Objekt
angewandt werden können.

=head2 new

Erzeuge ein MBMan - Objekt.

Beispiel:

  my $mbman = MBMan->new(%args) || die "new failed: $@\n";

=head2 connect

Verbinde mit einem IMAP4-Server.

Beispiel:

  $mbman->connect(
      Server => 'imap.server.tld'
  ) || die "Connection failed: $@\n";

=head2 login

=head2 unshift_message

=head2 limit_reached

=head2 logout

=head2 save_massage

=head2 folders

=head2 quota

=head2 notes

=head2 new_database

=head2 database_exists

=cut
